country_eic = {
    '10YAT-APG------L': 'Austria',
    '10YBE----------2': 'Belgium',
    '10YBA-JPCC-----D': 'Bosnia and Herzegovina',
    '10YCA-BULGARIA-R': 'Bulgaria',
    '10YHR-HEP------M': 'Croatia',
    '10YCY-1001A0003J': 'Cyprus',
    '10YCZ-CEPS-----N': 'Czech Republic',
    '10YFI-1--------U': 'Finland',
    '10YFR-RTE------C': 'France',
    '10Y1001A1001A83F': 'Germany',
    '10YGR-HTSO-----Y': 'Greece',
    '10YHU-MAVIR----U': 'Hungary',
    '10YIE-1001A00010': 'Ireland',
    '10YIT-GRTN-----B': 'Italy',
    '10YLV-1001A00074': 'Latvia',
    '10YLT-1001A0008Q': 'Lithuania',
    '10YLU-CEGEDEL-NQ': 'Luxembourg',
    '10YCS-CG-TSO---S': 'Montenegro',
    '10YNL----------L': 'Netherlands',
    '10YMK-MEPSO----8': 'North Macedonia',
    '10YNO-0--------C': 'Norway',
    '10YPL-AREA-----S': 'Poland',
    '10YPT-REN------W': 'Portugal',
    '10YRO-TEL------P': 'Romania',
    '10YCS-SERBIATSOV': 'Serbia',
    '10YSK-SEPS-----K': 'Slovakia',
    '10YSI-ELES-----O': 'Slovenia',
    '10YES-REE------0': 'Spain',
    '10YSE-1--------K': 'Sweden',
    '10YCH-SWISSGRIDZ': 'Switzerland'
}